[package]
name = "sketchover"
version = "0.3.1"
edition = "2021"

[dependencies]
winit = "0.30.8"
tray-icon = "0.19.2"
global-hotkey = "0.6.3"
mouse_position = "0.1.4"
softbuffer = "0.4.6"
ico = "0.4.0"
